# Generated by Django 2.0.6 on 2018-06-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180611_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_is_save',
            field=models.BooleanField(default=False),
        ),
    ]
