# Generated by Django 2.0.6 on 2018-06-12 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_article_article_touxiang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_auth',
        ),
        migrations.DeleteModel(
            name='Auth',
        ),
    ]
