# Generated by Django 2.0.6 on 2018-06-13 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180612_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='blog.UserSite'),
        ),
    ]
