# Generated by Django 2.0.6 on 2018-07-26 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180613_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Article', to='blog.ArticleClass'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_article',
            field=models.ManyToManyField(related_name='User', to='blog.Article'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_article_class',
            field=models.ManyToManyField(related_name='User', to='blog.ArticleClass'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_head',
            field=models.CharField(default='def.jpg', max_length=1024),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to='blog.UserSite'),
        ),
    ]
